import React from "react";
import Head from "next/head";
import styles from "../styles/AboutUs.module.scss";

function aboutUs() {
  return (
    <div className={styles.about}>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Section */}

      <div className={styles.main}>
        <video autoPlay muted loop className={styles.video}>
          <source src="/videos/drone.mp4" type="video/mp4" />
        </video>

        <div className={styles.mainTitle}>
          <h1>ABOUT US</h1>
        </div>
      </div>

      {/* Our Start Section */}
      <div className={styles.start}>
        <img src="/images/inside_stairs.jpg" alt="Image of stairs" />
        <div className={styles.text}>
          <h2>OUR START</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Dignissim cras tincidunt lobortis feugiat. Adipiscing elit ut
            aliquam purus sit amet luctus venenatis lectus. Non quam lacus
            suspendisse faucibus interdum posuere lorem ipsum dolor. Adipiscing
            diam donec adipiscing tristique risus nec. Gravida rutrum quisque
            non tellus orci. Egestas egestas fringilla phasellus faucibus
            scelerisque eleifend donec pretium vulputate. Tellus pellentesque eu
            tincidunt tortor aliquam nulla facilisi. Duis at consectetur lorem
            donec massa sapien faucibus et. Sollicitudin ac orci phasellus
            egestas tellus rutrum tellus pellentesque. In pellentesque massa
            placerat duis ultricies. Cras tincidunt lobortis feugiat vivamus at.
          </p>
        </div>
      </div>

      {/* Our Goals Section */}
      <div className={styles.goals}>
        <div className={styles.text}>
          <h2>OUR GOALS</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Dignissim cras tincidunt lobortis feugiat. Adipiscing elit ut
            aliquam purus sit amet luctus venenatis lectus. Non quam lacus
            suspendisse faucibus interdum posuere lorem ipsum dolor. Adipiscing
            diam donec adipiscing tristique risus nec. Gravida rutrum quisque
            non tellus orci.
          </p>
        </div>
        <img src="/images/inside_kitchen.jpg" alt="Image of a kitchen" />
      </div>
    </div>
  );
}

export default aboutUs;
