import React from "react";
import Link from "next/link";
import Head from "next/head";
import styles from "../../styles/Property.module.scss";

import Contact from "../../Components/Contact";

import listings from "../../public/data/listings.json";

function Property({ listing }) {
  return (
    <div className={styles.property}>
      <Head>
        <title>{listing.street}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Section */}

      <div className={styles.main}>
        <Link href="/properties">
          <img className={styles.back} src="/svg/back.svg" alt="Back icon" />
        </Link>
        <img
          className={styles.bg}
          src={`/images/listings/covers${listing.imgUrl}`}
          alt="Image of the property"
        />

        <div className={styles.mainTitle}>
          <h1>{listing.street}</h1>
          <h3>{listing.city}</h3>
        </div>
      </div>

      {/* Numbers Section */}
      <div className={styles.numbers}>
        <div className={styles.top}>
          <div className={styles.number}>
            <h3>${listing.price.toLocaleString("en-US")}</h3>
            <p>PRICE</p>
          </div>
          <div className={styles.number}>
            <h3>{listing.bedrooms}</h3>
            <p>BEDROOMS</p>
          </div>
        </div>
        <div className={styles.bottom}>
          <div className={styles.number}>
            <h3>{listing.bathrooms}</h3>
            <p>BATHROOMS</p>
          </div>
          <div className={styles.number}>
            <h3>{listing.size.toLocaleString("en-US")}</h3>
            <p>SQUARE FEET</p>
          </div>
        </div>
      </div>

      {/* About Section */}

      <div className={styles.about}>
        <div className={styles.text}>
          <h2>ABOUT</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Dignissim cras tincidunt lobortis feugiat. Adipiscing elit ut
            aliquam purus sit amet luctus venenatis lectus. Non quam lacus
            suspendisse faucibus interdum posuere lorem ipsum dolor. Adipiscing
            diam donec adipiscing tristique risus nec. Gravida rutrum quisque
            non tellus orci.
          </p>
        </div>
        <img
          src={`/images/listings/thumbnails${listing.imgUrl}`}
          alt="Image of the property"
        />
      </div>

      {/* Carousel Section */}
      {/* <Carousel /> */}

      {/* Google Maps Section */}

      <iframe
        className={styles.map}
        src={listing.googleMaps}
        width="100%"
        style={{ border: 0 }}
        allowFullScreen="true"
        loading="lazy"
      ></iframe>

      {/* Enquire Section */}

      <Contact title="ARE YOU INTERESTED?" />
    </div>
  );
}

export async function getStaticPaths() {
  const paths = listings.map((listing) => ({
    params: { id: listing.id.toString() },
  }));

  return { paths, fallback: false };
}

// This also gets called at build time
export async function getStaticProps({ params }) {
  return {
    props: {
      listing: listings.find((listing) => listing.id == params.id),
    },
  };
}

export default Property;
