import React from "react";
import Head from "next/head";
import styles from "../../styles/Property.module.scss";

import Contact from "../../Components/Contact";
import Carousel from "../../Components/Carousel";

function Property() {
  return (
    <div className={styles.property}>
      <Head>
        <title>Property</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Section */}

      <div className={styles.main}>
        <img
          className={styles.bg}
          src="/images/villa_pool_2.jpg"
          alt="Image of the property"
        />

        <div className={styles.mainTitle}>
          <h1>12345 STREET</h1>
          <h3>LOS ANGELES, CA</h3>
        </div>
      </div>

      {/* Numbers Section */}
      <div className={styles.numbers}>
        <div className={styles.top}>
          <div className={styles.number}>
            <h3>$1,500,000</h3>
            <p>PRICE</p>
          </div>
          <div className={styles.number}>
            <h3>4</h3>
            <p>BEDROOMS</p>
          </div>
        </div>
        <div className={styles.bottom}>
          <div className={styles.number}>
            <h3>6</h3>
            <p>BATHROOMS</p>
          </div>
          <div className={styles.number}>
            <h3>10,000</h3>
            <p>SQUARE FEET</p>
          </div>
        </div>
      </div>

      {/* About Section */}

      <div className={styles.about}>
        <div className={styles.text}>
          <h2>ABOUT</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Dignissim cras tincidunt lobortis feugiat. Adipiscing elit ut
            aliquam purus sit amet luctus venenatis lectus. Non quam lacus
            suspendisse faucibus interdum posuere lorem ipsum dolor. Adipiscing
            diam donec adipiscing tristique risus nec. Gravida rutrum quisque
            non tellus orci.
          </p>
        </div>
        <img src="/images/villa_pool_2.jpg" alt="Image of the property" />
      </div>

      {/* Carousel Section */}
      {/* <Carousel /> */}

      {/* Google Maps Section */}

      <iframe
        className={styles.map}
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3105.1501993708557!2d-77.03871848432898!3d38.89768045453188!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89b7b7bcdecbb1df%3A0x715969d86d0b76bf!2sBijela%20ku%C4%87a!5e0!3m2!1shr!2shr!4v1639677514826!5m2!1shr!2shr"
        width="100%"
        style={{ border: 0 }}
        allowFullScreen="true"
        loading="lazy"
      ></iframe>

      {/* Enquire Section */}

      <Contact title="ENQUIRE" />
    </div>
  );
}

export default Property;
